name: Flutter Web
on:
  push:
    branches:
      - test/actionTest
jobs:
  build:
    name: Build Web
    env:
      my_secret: $
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: setting environment
        uses: subosito/flutter-action@v1
        with:
          channel: 'dev'
      - name: flutter build
        run: |
             flutter config --enable-web
             flutter pub get
             flutter build web --release
      - name: find directory
        run: |
            ls
      - name: deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: build/web # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch
#           cd build/web
#           git init
#           git config --global user.email kyshim9004@gmail.com
#           git config --global user.name "Keonyoung Shim"
#           git status
#           git remote add origin https://${{secrets.commit_secret}}@github.com/k-young-passionate/Password-Generator-Flutter.git 
#           git checkout -b gh-pages
#           git add --all
#           git commit -m "update"
#           git push origin gh-pages -f


