name: Flutter Web
on:
  push:
    branches:
      - master
jobs:
  build_and_deploy:
    name: Build Web
#     env:
#       my_secret: $
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: setting environment
        uses: subosito/flutter-action@v1
        with:
          channel: 'dev'
      - name: flutter build
        run: |
             flutter config --enable-web
             flutter pub get
             flutter build web --release
      - name: deploy to gh-pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: build/web # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch
